# Hosts all your test and deployment configuration.
# https://scrutinizer-ci.com/docs/configuration/build
build:
    nodes:
        analysis:
            dependencies:
                before:
                    # If Wordpress itself is not a dependency of your project, Scrutinizer will not recognize WP project.
                    - 'composer require --dev johnpbloch/wordpress'
            project_setup:
                override: true
            tests:
                override:
                    - php-scrutinizer-run --enable-security-analysis

# Allows to customize how your code is analyzed.
checks:
  php:
    verify_argument_usable_as_reference: false
    verify_property_names: false
    no_global_keyword: false
    psr2_class_declaration: false
    avoid_superglobals: false
    one_class_per_file: false
    code_rating: true
    no_exit: false
    side_effects_or_types: false
    coding_standard:
        name: WordPress

# Defines which files to analyze.
filter:
    dependency_paths:
        - wordpress/
    excluded_paths:
        - "tmp/"
        - "vendor/"
        - "node_modules/"

# Defines how your code should generally look like.
coding_style:
    php:
        indentation:
            general:
                use_tabs: true
        spaces:
            around_operators:
                concatenation: true
                negation: true
            within:
                brackets: true
                grouping: true
                function_call: true
                function_declaration: true
                if: true
                for: true
                while: true
                switch: true
                catch: true
                type_cast: true

tools:
  sensiolabs_security_checker: true
  # external_code_coverage: true
  php_code_sniffer:
      config:
          # https://scrutinizer-ci.com/docs/tools/php/code-sniffer/standards
          standard: "WordPress"


